# Site settings
title:  展翅高飞的个人博客
email:  jxfflying@163.com
github: jxffly
description: > # this means to ignore newlines until "baseurl:"
  这个是我的个人博客，写的不好的地方请见谅
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/jxffly" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
# weibo:    ID
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-feed

